# Generated by Django 5.2.2 on 2025-06-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bk_task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
