# Generated by Django 5.2.2 on 2025-06-06 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bk_task', '0003_alter_task_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
